### ISSUE TITLE
Thrift has docker support

### ISSUE THREAD

**Issue by jeking3** [ahawkins/docker-thrift#12]
Please see:
https://github.com/apache/thrift/tree/master/build/docker

**Comment by tianon** [comment]
@jeking3 if upstream is interested, we (the official images team) would happily welcome maintenance of https://github.com/docker-library/official-images/blob/master/library/thrift directly by upstream (if interested, see https://github.com/docker-library/official-images#readme for more details regarding the program)

**Comment by jeking3** [comment]
This looks pretty specific to supporting go?

Currently the thrift project provides a docker image for building thrift which contains all of the supported languages (well, as many as possible; some like Cocoa are not represented due to obvious reasons).

Given thrift only has one executable to run which is typically linked statically, it's really up to the consumer to provide a runtime environment for the language their project is going to use, and to ensure the proper dependencies for Thrift are provided.  I'm not certain that having docker images for thrift consumption is generically applicable.  The containers in the official repo used to provide the build environment though - those are invaluable.

**Comment by lag-linaro** [comment]
@jeking3 it's great that Thrift upstream provide an easy to consume build platform using Docker.  However the intentions and use-cases are different when compared to the ones of this project.  The images maintained and produced by the Docker Official Images project provide pre-installed systems which function out-of-the-box.  They are a first class resource for any users who wish to quickly and easily investigate the merits of a project before going ahead with their own, possibly bespoke, install.

It looks like there are >1,000,000 pulls of this image, which must tell you something.

Taking what you say into consideration, perhaps one `thrift` Official Image is not the way to go.

Would images maintained by upstream akin to `thrift-go`, `thrift-ruby`, etc be an option?

Maybe `thrift` i.e. `docker pull thrift` could be the default, `go` perhaps?

**Comment by jeking3** [comment]
I agree with you that most likely each language supported could provide a docker image with the thrift compiler as well as a pre-installed language runtime with the thrift runtime libraries.  That said, given we're moving towards providing integration with as many package managers as possible, for more languages it will be possible to add one line to an existing docker image that will include thrift in the language runtime.

I'm wondering what the requirements that end-users downloading this package are making?  There is one docker image for building thrift which we already use to run our CI jobs on Travis.  It gives you a docker image with runtime for as many languages as possible, but it's pretty big and that's not typically what folks are looking for.

We can certainly point these builds at tags in the official Apache Thrift repo, and if we need to add anything to the repo we can do that in future releases.  Issues I see with the Dockerfile at https://github.com/ahawkins/docker-thrift/blob/master/0.11/Dockerfile would be:

1. If you are not building the cpp library then you should not need boost.
2. It bases off debian wheezy, which may not be what people need.
3. We don't support go before v1.7 any more, and that Dockerfile has v1.4.

People have so many different requirements for production runtime environments, satisfying them with one Dockerfile seems like it is going to be rare.

**Comment by tianon** [comment]
@jeking3 as another alternative, perhaps we simply deprecate `thrift` itself with some links to appropriate documentation for what to replace it with?  See for example https://hub.docker.com/_/django, which is a framework for Python applications and thus suffered from a similar problem (and was eventually deprecated for similar reasons).

**Comment by jeking3** [comment]
The only benefit I see here is that it provides a runtime environment in which you can run the thrift compiler, however that only generates code.  You still need a language runtime to use it, and they aren't in this package.  As such, I'm not sure what the usefulness of this official image is right now to a consumer of thrift.

**Comment by jeking3** [comment]
If we could find out why the image has been pulled 1 million times, perhaps that would help. :)

**Comment by lag-linaro** [comment]
I guess @ahawkins would be a good place to start. :smiley:

**Comment by tianon** [comment]
As it stands, this image is sorely outdated (and thus poorly representing Thrift anyhow) -- for example, Wheezy has been unsupported for a while now.  We either need an update, a replacement, or a deprecation.

**Comment by lag-linaro** [comment]
Agreed.

I think @jeking3 should create a set of useful DockerHub images and support AArch64 by default. :smile:

**Comment by jeking3** [comment]
I recently got the permission I need to make official thrift compiler docker images that can be released under the official Apache Thrift docker account.  I just haven't gotten to it.  We're planning to start the next release cycle for Thrift as well, which will take priority, among the myriad other things I've oversubscribed myself to. :)

I recently was able to provide different architecture build environments for boost in the boostorg/bdde project.  This allows one to build and test a big-endian ppc architecture for example on x86_64.  Note however that the thrift compiler will run fine in a x86_64 container and produce identical code to the same compiler running in an aarch64 container, so I'm not sure what the exact need would be for an aarch64 based thrift compiler container.

**Comment by lag-linaro** [comment]
The container doesn't have to be different.

You just have to list support for `arm64v8` in the `architectures` tag. 

See the Ubuntu library file for an example: [Official Images - Ubuntu Library File](https://github.com/docker-library/official-images/blob/master/library/ubuntu).

**Comment by tianon** [comment]
@jeking3 awesome! :tada:  So should we plan to replace this image's source with the new thing you create, or should we deprecate this image instead pointing to your images as the suggested alternative? :heart:

**Comment by jeking3** [comment]
Wait for other images to be available first. :)

**Comment by lag-linaro** [comment]
Any update on this @jeking3?

I would love to see the official Docker Hub version of Thrift maintained again.

**Comment by tianon** [comment]
The `thrift` image has now gone over 300 days since it was last updated -- any chance of getting it updated (or the aforementioned replacement taking over)?

**Comment by bradfordlemley** [comment]
@tianon Since this repo seems to be unmaintained, would you be able to accept an update from somewhere else?  Looks like @yuokada has the update ready at https://github.com/ahawkins/docker-thrift/pull/22.

**Comment by tianon** [comment]
That would be great (assuming there's also some commitment to keep the new thing updated), although I am curious about @jeking3's upstream replacement status. :smile:

**Comment by tianon** [comment]
Friendly ping @jeking3 -- any status on that upstream initiative? :pray:
