### ISSUE TITLE
Generated go files import thrift using strange path.

### ISSUE THREAD

**Issue by davinchia** [ahawkins/docker-thrift#7]
All my generated go files are importing thrift using `git.apache.org/thrift.git/lib/go/thrift`. To my knowledge it is not typical for go folders to have `.git` in their name. Is this behaviour intentional? Or it this a bug?

**Comment by toneill818** [comment]
This is the correct behavior. git.apache.org/thrift.git/lib/go/thrift is the path where the golang files are store. You can see an example go client and server from Thrift's documentation [here](https://thrift.apache.org/tutorial/go). 

`git.apache.org/thrift.git/lib/go/thrift`
